### ISSUE TITLE
Correct way to change code in CustomControlLibrary.WpfCore.DesignTools project to avoid blocking CustomControlLibrary.WpfCore.DesignTools.dll by IDE.

### ISSUE THREAD

**Issue by dmitrybv** [microsoft/xaml-designer-extensibility#38] opened 2021-01-23 19:07 UTC
What is the correct way to change code in CustomControlLibrary.WpfCore.DesignTools project?
Every time I change code in files of CustomControlLibrary.WpfCore.DesignTools project and try to recompile solution I get the error 
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning		Unable to delete file "C:\DelphiStuff\DotNet Samples\github-ms-xaml-dsgn-ext\Prj\samples\CustCntLib.WpfCore\CustomControlLibrary.WpfCore\bin\Debug\netcoreapp3.0\CustomControlLibrary.WpfCore.DesignTools.dll". Access to the path 'C:\DelphiStuff\DotNet Samples\github-ms-xaml-dsgn-ext\Prj\samples\CustCntLib.WpfCore\CustomControlLibrary.WpfCore\bin\Debug\netcoreapp3.0\CustomControlLibrary.WpfCore.DesignTools.dll' is denied.	CustomControlLibrary.WpfCore.DesignTools			

```
So I should to close and reopen Visual Studio to recompile changed code.

Looks like it is a duplicate of issue #13.

**Comment by dmitrybv** [comment] 2021-01-23 19:23
One solution I have found is to use an extension to restart visual studio.
'Visual Studio Restart' - https://marketplace.visualstudio.com/items?itemName=PaulMelia.VsRestart001&ssr=false#overview

**Comment by lutzroeder** [comment] 2021-01-25 22:33
Duplicate of #13

**Closed by lutzroeder** 2021-01-25 22:33 UTC
